---
title: Extras
---

<h1 class="titulo">
  Materiais Extras
</h1>

## Vídeos

<a href="https://www.youtube.com/channel/UCCo5fq-1LJOGzDkBGTCqH7Q" target="_blank">
  Canal do monitor Henrique Saraiva</a>. Ensino eficiente - canal desenvolvido pelo monitor Henrique Saraiva para desenvolvimento de conteúdo: auxílio na elaboração de vídeo, edição de vídeo, gravação, etc.

<a href="https://www.youtube.com/watch?v=Sm5xF-UYgdg" target="_blank">
  Como não ser ignorante sobre o mundo
</a>

<a href="https://pt.khanacademy.org/math/probability" target="_blank">
  Khanacademy academy
</a>

<a href="https://www.youtube.com/channel/UCmt35xKrpPavoT0iq1EqOVQ" target="_blank">
  Canal da Suzi Samá, professora da FURG
</a>

<a href="https://drive.google.com/file/d/1Z94N6gRskqv0N_7EWeWldON0_opwdpsN/view" target="_blank">
  Resolução do exercício 16 - Lista 1.4 e 1.5
</a>





## Tabelas

[Resumo de Teste de Hipóteses](material/tabela_resumo_de_teste_de_hipotese.pdf)

[Tabelas das distribuições Z, T, Qui-Quadrado e F](material/tabelas_z_t_chi_f.pdf)

## Apostilas

[Livro de Estatística Básica](material/apostila_de_estatistica_basica.pdf)

[Apostila de Regressão Linear Simples](material/apostila_de_regressao_linear.pdf)

## Aplicações WEB

<a href="https://brunamdalmoro.shinyapps.io/Descritivas/" target="_blank">
  Gráficos e Medidas Descritivas
</a>

Nesta aplicação é possível exercitar os conceitos de representação gráfica e de medidas descritivas, vistos nas aulas: 
1.3 Representações gráficas e 1.4 Medidas descritivas que podem ser acessadas na aba [Vídeos](/probabilidade-estatistica/videos/index.html).

O aplicativo possui três abas:

(@) Dados - É possível selecionar o banco de dados para fazer as análises. Uma breve descrição do banco de dados e de suas variáveis é apresentado.

(@) Gráficos - É possível escolher o gráfico que deseja utilizar. Logo abaixo é apresentada uma breve descrição do tipo de gráfico e ao lado seleciona-se as variáveis.

(@) Est. Descritivas - É possível selecionar a variável que se deseja analisar e ao lado é apresentada uma tabela com as medidas descritivas calculadas.


<a href="https://brunamdalmoro.shinyapps.io/TCL_medias/" target="_blank">
  Distribuições amostrais e TCL
</a>

Nesta aplicação é possível exercitar os conceitos vistos na aula 2.3 Distribuições amostrais e TCL que pode ser acessada na aba [Vídeos](/probabilidade-estatistica/videos/index.html).

O aplicativo possui duas abas:

(@) Simulação - É onde a simulação é feita, para entender as Distribuições Amostrais e o Teorema Central do Limite.

(@) Como Usar - É apresentada uma breve descrição sobre o teorema e explica como funciona o app, explicando como utilizar os controles e como interpretar os gráficos apresentados.






