---
title: Probcast
---

<h1 class="titulo"> 
  probcast - O Podcast da Probabilidade e Estatística!
</h1>

## Episódio 1

<p align="justify">
  Probabilidade e Estatística: Pra quê serve tudo isso? Parte 1 (com Prof. Márcia Barbian e Prof. Markus Stein)
</p>

<a href="episodios/ep1.mp3">
  Clique aqui para ouvir o episódio 1
</a>

## Episódio 2

<p align="justify">
Probabilidade e Estatística: Pra quê serve tudo isso? Parte 2 (com Prof. Lisiane Selau)
</p>

<a href="episodios/ep2.mp3">
  Clique aqui para ouvir o episódio 2
</a>

## Episódio 3

<p align="justify">
O Dicionário da Probabilidade e Estatística: os termos fundamentais para acompanhar o semestre "de boa" (com Prof. Márcia Barbian e Prof. Markus Stein)
</p>

<a href="episodios/ep3.mp3">
  Clique aqui para ouvir o episódio 3
</a>

## Episódio 4

<p align="justify">
Aprendendo a ensinar estatística - com a Profª. Luciana Nunes 

Sobre este Episódio: Nesta edição especial para futuros educadores, conversaremos sobre como ensinar estatística para crianças pode ser mais fácil do que você imagina.
</p>

<div class="row">

<div class="col-md-5 col-lg-5">
  <iframe width="200%" height="315" src="https://www.youtube.com/embed/mLFaymPt8Dk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
</div>


## Episódio 5

<p align="justify">
Entendendo uma pandemia com estatística - Professores Luís Vidaletti Ruas e Rodrigo dos Reis

Sobre este Episódio: Nesta edição, conversaremos com os professores Luidi e Rodrigo sobre como utilizar estatística para compreender uma pandemia. 
</p>

<div class="row">

<div class="col-md-5 col-lg-5">
  <iframe width="200%" height="315" src="https://www.youtube.com/embed/8FfsrQgLfCE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
  </iframe>
</div>


